# Generated by Django 4.2.6 on 2023-10-19 15:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.image_upload),
        ),
    ]
