# Generated by Django 4.2.6 on 2024-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
