# Generated by Django 4.2.6 on 2024-10-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_serviceprovider_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_name',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='company',
            field=models.TextField(null=True),
        ),
    ]
