# Generated by Django 4.2.6 on 2023-10-28 07:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='avatar',
            new_name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.image_upload),
        ),
    ]
