# Generated by Django 4.2.6 on 2023-10-29 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
