# Generated by Django 4.2.6 on 2024-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
