# Generated by Django 4.2.6 on 2024-03-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_worker_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='ServiceProvider',
        ),
    ]
