# Generated by Django 4.2.6 on 2024-07-19 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_latitude_property_longitude'),
        ('users', '0022_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property'),
        ),
    ]
