# Generated by Django 4.2.6 on 2024-07-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_tenant_property_user_admin_access_allowed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin_access_allowed',
            new_name='allow_access_account',
        ),
    ]
