# Generated by Django 4.2.6 on 2024-07-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_admin_access_allowed_user_allow_access_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_slug',
            field=models.SlugField(blank=True),
        ),
    ]
