# Generated by Django 4.2.6 on 2024-08-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_contactus_created_at_contactus_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
