# Generated by Django 4.2.6 on 2024-08-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_tenant_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
