# Generated by Django 4.2.6 on 2024-08-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_tenant_email_alter_tenant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together=set(),
        ),
    ]
