# Generated by Django 4.2.6 on 2024-10-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_subscription_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
