# Generated by Django 4.2.6 on 2024-11-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription_subscription_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='payment_id',
            new_name='_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='tax',
        ),
    ]
