# Generated by Django 4.2.6 on 2024-04-01 14:39

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_tenantsfeedback_is_done_tenantsfeedback_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsfeedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=feedback.models.tenant_feedback_image),
        ),
    ]
