# Generated by Django 4.2.6 on 2024-07-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_tenantsfeedback_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminfeedback',
            name='is_archieve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsfeedback',
            name='is_archieve',
            field=models.BooleanField(default=False),
        ),
    ]
