# Generated by Django 4.2.6 on 2024-07-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_adminfeedback_is_archieve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminfeedback',
            old_name='is_archieve',
            new_name='is_archive',
        ),
        migrations.RenameField(
            model_name='tenantsfeedback',
            old_name='is_archieve',
            new_name='is_archive',
        ),
    ]
