# Generated by Django 4.2.6 on 2024-08-18 09:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0031_user_subscription_status'),
        ('feedback', '0007_rename_is_archieve_adminfeedback_is_archive_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantsFeedback',
            new_name='UserFeedback',
        ),
    ]
