# Generated by Django 4.2.6 on 2024-08-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_latitude_property_longitude'),
        ('feedback', '0008_rename_tenantsfeedback_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property'),
        ),
    ]
