# Generated by Django 4.2.6 on 2024-08-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_latitude_property_longitude'),
        ('feedback', '0009_userfeedback_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
