# Generated by Django 4.2.6 on 2023-12-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_development_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevelopmentservices',
            name='started_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
