# Generated by Django 4.2.6 on 2024-10-06 09:47

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_antal_bostäder_and_more'),
        ('services', '0002_maintenance_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foretag', models.TextField()),
                ('namn', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
                ('e_post', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dokument', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usermaintenanceservices',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='admin_services_properties', to='property.property'),
        ),
        migrations.CreateModel(
            name='SeviceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=services.models.service_document)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='services.servicedocumentfolder')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSelfServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benamning_av_tjanst', models.CharField(max_length=255)),
                ('Kostnad_per_manad', models.CharField(max_length=255)),
                ('beskrivning', models.TextField(blank=True, null=True)),
                ('startdatum_for_underhallstjanst', models.DateField(blank=True, null=True)),
                ('hur_ofta_utfor_denna_tjanst', models.CharField(blank=True, max_length=255, null=True)),
                ('fortydligande_av_tjanstens_frekvens', models.TextField(blank=True, null=True)),
                ('access', models.TextField(blank=True, null=True)),
                ('anteckningar', models.TextField(blank=True, null=True)),
                ('kontaktuppgifter_till_ansvarig_leverantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_service_provider', to='services.selfserviceprovider')),
                ('relevanta_dokument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relevanta_dokument', to='services.servicedocumentfolder')),
                ('vilka_byggnader_omfattas', models.ManyToManyField(related_name='self_service_properties', to='property.property')),
            ],
        ),
    ]
