# Generated by Django 4.2.6 on 2023-12-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_userdevelopmentservices_started_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevelopmentservices',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
