# Generated by Django 4.2.6 on 2024-10-06 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_selfserviceprovider_servicedocumentfolder_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeviceDocument',
            new_name='ServiceDocument',
        ),
        migrations.RenameField(
            model_name='externalselfservices',
            old_name='Kostnad_per_manad',
            new_name='kostnad_per_manad',
        ),
        migrations.AddField(
            model_name='externalselfservices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalselfservices',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
