# Generated by Django 4.2.6 on 2023-12-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_userdevelopmentservices_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevelopmentservices',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed')], max_length=10),
        ),
    ]
