# Generated by Django 4.2.6 on 2023-12-24 20:40

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_userdevelopmentservices_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.models.service_images)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userdevelopmentservices',
            name='started_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
