# Generated by Django 4.2.6 on 2024-10-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_externalselfservices_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalselfservices',
            name='relevanta_dokument',
        ),
        migrations.AddField(
            model_name='servicedocumentfolder',
            name='external_self_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_folder', to='services.externalselfservices'),
        ),
    ]
