# Generated by Django 4.2.6 on 2024-10-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_externalselfservices_relevanta_dokument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedocumentfolder',
            old_name='external_self_service',
            new_name='manual_service',
        ),
    ]
