# Generated by Django 4.2.6 on 2023-12-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_maintance_alter_userdevelopmentservices_started_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintance',
            new_name='Maintenance',
        ),
    ]
