# Generated by Django 4.2.6 on 2023-12-24 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0007_rename_maintance_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaintenanceServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed')], max_length=10)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_services', to='services.maintenance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
