# Generated by Django 4.2.6 on 2024-10-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_servicedocument_servicefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaintenanceServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_clarification', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=10)),
                ('access_details', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('day', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.RemoveField(
            model_name='usermaintenanceservices',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='usermaintenanceservices',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='usermaintenanceservices',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='usermaintenanceservices',
            name='user',
        ),
    ]
