# Generated by Django 4.2.6 on 2024-10-12 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_antal_bostäder_and_more'),
        ('notifications', '0003_alter_adminnotifications_maintenance'),
        ('users', '0006_serviceprovider_email'),
        ('services', '0009_ordermaintenanceservices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMaintenanceServices',
        ),
        migrations.AddField(
            model_name='ordermaintenanceservices',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_services', to='services.maintenance'),
        ),
        migrations.AddField(
            model_name='ordermaintenanceservices',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='admin_services_properties', to='property.property'),
        ),
        migrations.AddField(
            model_name='ordermaintenanceservices',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_provider', to='users.serviceprovider'),
        ),
        migrations.AddField(
            model_name='ordermaintenanceservices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_maintenance', to=settings.AUTH_USER_MODEL),
        ),
    ]
