# Generated by Django 4.2.6 on 2024-10-12 21:33

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_delete_usermaintenanceservices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServiceDocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dokument', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ordermaintenanceservices',
            old_name='date',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='ordermaintenanceservices',
            name='day',
        ),
        migrations.RemoveField(
            model_name='ordermaintenanceservices',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ordermaintenanceservices',
            name='time',
        ),
        migrations.AlterField(
            model_name='ordermaintenanceservices',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OrderServiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=services.models.service_document)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='services.orderservicedocumentfolder')),
            ],
        ),
        migrations.AddField(
            model_name='orderservicedocumentfolder',
            name='order_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_folder', to='services.ordermaintenanceservices'),
        ),
    ]
