# Generated by Django 4.2.6 on 2023-12-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_development_options_alter_maintenance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevelopmentservices',
            options={},
        ),
    ]
