# Generated by Django 4.2.6 on 2023-12-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_userdevelopmentservices_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevelopmentservices',
            options={'ordering': ['-pk']},
        ),
    ]
