# Generated by Django 4.2.6 on 2024-10-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_orderservicedocumentfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaintenanceservices',
            name='communication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordermaintenanceservices',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ordermaintenanceservices',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordermaintenanceservices',
            name='contact_telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
