# Generated by Django 4.2.6 on 2024-10-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_rename_communication_ordermaintenanceservices_communication_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaintenanceservices',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
