# Generated by Django 4.2.6 on 2024-01-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_development_type_maintenance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevelopmentservices',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermaintenanceservices',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
