# Generated by Django 4.2.6 on 2024-01-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_userdevelopmentservices_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='type',
        ),
    ]
