# Generated by Django 4.2.6 on 2024-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_maintenance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
