# Generated by Django 4.2.6 on 2024-02-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_document_property_document_folder_and_more'),
        ('services', '0016_alter_development_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevelopmentservices',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='development_property', to='property.property'),
        ),
        migrations.AddField(
            model_name='usermaintenanceservices',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintaince_property', to='property.property'),
        ),
    ]
