# Generated by Django 4.2.6 on 2024-03-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_worker_serviceprovider'),
        ('services', '0017_userdevelopmentservices_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaintenanceservices',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to='users.serviceprovider'),
        ),
    ]
