# Generated by Django 4.2.6 on 2024-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_usermaintenanceservices_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaintenanceservices',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermaintenanceservices',
            name='day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermaintenanceservices',
            name='frequency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermaintenanceservices',
            name='iteration',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Other', 'Other')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='usermaintenanceservices',
            name='time',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
    ]
