# Generated by Django 4.2.6 on 2023-10-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog-cover/'),
        ),
    ]
