# Generated by Django 4.2.6 on 2023-10-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_sendmail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_sendsms',
            field=models.BooleanField(default=False),
        ),
    ]
