# Generated by Django 4.2.6 on 2024-04-12 23:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_cover_photo_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.newsletter_cover),
        ),
    ]
