# Generated by Django 4.2.6 on 2024-04-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
