# Generated by Django 4.2.6 on 2024-07-28 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userweb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to=userweb.models.upload_miniwebsite_banner)),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
