# Generated by Django 4.2.6 on 2024-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userweb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="sub_title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
