# Generated by Django 4.2.6 on 2024-07-29 09:36

from django.db import migrations, models
import userweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0002_homepage_created_at_homepage_updated_at_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to=userweb.models.upload_miniwebsite_document),
        ),
    ]
