# Generated by Django 4.2.6 on 2024-08-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0004_usercontactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserContactUs',
        ),
    ]
