# Generated by Django 4.2.6 on 2024-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0006_documents_name_formlinks_contactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlinks',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
