# Generated by Django 4.2.6 on 2023-11-11 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byggand', models.CharField(max_length=255)),
                ('fond', models.CharField(max_length=255)),
                ('ansvarig_AM', models.CharField(max_length=255)),
                ('yta', models.CharField(max_length=255)),
                ('loa', models.CharField(max_length=255)),
                ('bta', models.CharField(max_length=255)),
                ('lokal_elproduktion', models.CharField(max_length=255)),
                ('installered_effekt', models.CharField(max_length=255)),
                ('geo_energi', models.CharField(max_length=255)),
                ('epc_tal', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=property.models.document_upload)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='property.property')),
            ],
        ),
    ]
