# Generated by Django 4.2.6 on 2023-11-11 22:19

from django.db import migrations, models
import django.utils.timezone
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_picture_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=property.models.picture_upload),
            preserve_default=False,
        ),
    ]
