# Generated by Django 4.2.6 on 2024-08-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "property",
            "0003_remove_property_address_remove_property_ansvarig_am_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="fjärrvärme",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="skyddsrum",
            field=models.BooleanField(null=True),
        ),
    ]
