# Generated by Django 4.2.6 on 2024-09-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_fjärrvärme_alter_property_skyddsrum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='snittarea_per_bostad',
        ),
        migrations.AddField(
            model_name='property',
            name='antal_våningar',
            field=models.CharField(max_length=255, null=True, verbose_name='Number of apartments'),
        ),
        migrations.AddField(
            model_name='property',
            name='fastighetsbeteckning',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='hiss',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='solpaneler',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='uppvärmningssystem',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ventilationssystem',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='fjärrvärme',
            field=models.BooleanField(default=True),
        ),
    ]
