# Generated by Django 4.2.6 on 2024-10-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_property_snittarea_per_bostad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='antal_bostäder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Number of apartments'),
        ),
        migrations.AlterField(
            model_name='property',
            name='antal_våningar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Number of apartments'),
        ),
        migrations.AlterField(
            model_name='property',
            name='boarea',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Total living area in building'),
        ),
        migrations.AlterField(
            model_name='property',
            name='byggår',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Construction year'),
        ),
        migrations.AlterField(
            model_name='property',
            name='fastighetsbeteckning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='fjärrvärme',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gatuadress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='hiss',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='postnummer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='skyddsrum',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='solpaneler',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='uppvärmningssystem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='ventilationssystem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
