# Generated by Django 4.2.6 on 2024-01-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0016_alter_development_type'),
        ('feedback', '0002_adminfeedback_created_at_adminfeedback_is_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.userdevelopmentservices')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.adminfeedback')),
                ('maintaince', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.usermaintenanceservices')),
            ],
        ),
    ]
