# Generated by Django 4.2.6 on 2024-08-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        ("services", "0001_initial"),
        ("feedback", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminnotifications",
            name="development",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.userdevelopmentservices",
            ),
        ),
        migrations.AddField(
            model_name="adminnotifications",
            name="feedback",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.adminfeedback",
            ),
        ),
        migrations.AddField(
            model_name="adminnotifications",
            name="maintenance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.usermaintenanceservices",
            ),
        ),
    ]
