# Generated by Django 4.2.6 on 2024-01-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_adminfeedback_created_at_adminfeedback_is_done_and_more'),
        ('notifications', '0002_remove_adminnotifications_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotifications',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.adminfeedback'),
        ),
    ]
