# Generated by Django 4.2.6 on 2024-08-11 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import economi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0009_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_transaction', models.CharField(max_length=255)),
                ('type_of_cost_or_revenue', models.CharField(max_length=255)),
                ('date_of_transaction', models.DateField()),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_added_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=economi.models.expense_file_upload)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_expenses', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
