# Generated by Django 4.2.6 on 2024-08-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_of_transaction',
            field=models.DateField(null=True),
        ),
    ]
