# Generated by Django 4.2.6 on 2024-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economi', '0002_alter_expense_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='value_added_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
