# Generated by Django 4.2.6 on 2024-11-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economi', '0003_alter_expense_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='value_added_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
